upload-lesson/config/routes.rb
UploadLesson::Application.routes.draw do
  resources :assets
  resources :lessons
  resources :courses, :has_many => :comments
  
  root :to => "home#index"
  match "home" => "home#index"
  match "download" => "lessons#download"
  match "downloadcourse" => "courses#downloadcourse"

end

upload-lesson/app/models/lesson.rb
require 'zip/zip'
require 'zip/zipfilesystem'

class Lesson < ActiveRecord::Base
  attr_accessible :attachment, :course_id, :goal, :title, :assets_attributes
  belongs_to :course
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :reject_if => lambda { |a| a[:asset_file_name].blank? }


  def bundle
    t = Course.find(self.course_id)
#create the ZIPfile with the title of lesson_id
    bundle_filename = "public/attachments/lessons/#{self.id}/#{t.name}_#{self.title}.zip"
    FileUtils.rm "public/attachments/lessons/#{self.id}/#{t.name}_#{self.title}.zip", :force => true #remove in case it exists

     dir = "public/attachments/lessons/#{self.id}" #directory of the lesson
    
#open the ZIPfile in order to add items in
     Zip::ZipFile.open(bundle_filename, Zip::ZipFile::CREATE) {
       |zipfile|
       Dir.foreach(dir) do |item|
#for each "item" in the Dir, do the following..
        item_path = "#{dir}/#{item}"
         zipfile.add(item, item_path) if File.file? item_path
       end
      }
#change permissions on ZIPfile
  File.chmod(0644, bundle_filename)
  self.save
  end

  def download
    send_file "/public/attachments/lessons/#{self.id}/#{t.name}_#{self.title}.zip", :type=>"application/zip" 
  end
end

upload-lesson/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
      format.zip
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
   @lesson = Course.find(params[:course_id]).lessons.build   
   3.times { @lesson.assets.build } 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
    3.times { @lesson.assets.build } 

  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])
   
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    FileUtils.rm_rf "#{Rails.root}/public/attachments/lessons/#{@lesson.id}"
#removes the lesson directory in public/attachments
    @lesson.destroy
    
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end

def download
  les = Lesson.find(params[:file_name])
  co = Course.find(les.course_id)
  send_file "#{Rails.root}/public/attachments/lessons/#{les.id}/#{co.name}_#{les.title}.zip", :type=>"application/zip" 
end

end

upload-lesson/app/helpers/lessons_helper.rb
module LessonsHelper
end

upload-lesson/app/views/lessons/_asset_fields.html.erb
<p class ="fields">
 
    <%= f.file_field :asset %>        
    <%= f.hidden_field :_destroy %>
<br>
    <%= link_to_function "remove", "remove_fields(this)" %>

<br>
</p>

upload-lesson/app/views/lessons/_form.html.erb
<%= form_for @lesson, :html => { :multipart => true} do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :title, :placeholder => "Title of Lesson.." %>Title
  </div>
  <div class="field">

    <%= f.text_field :goal, :placeholder => "Goal of Lesson.." %>Goal
  </div>

<p>
    <% f.fields_for :assets do |builder| %>
    <% render 'asset_fields', :f => builder %><br>
    <% end %>
</p>

  <div class="field">

    <%= f.hidden_field :course_id %>
  </div>

  <div class="actions">

<button type="submit" class="btn btn-primary">
  <i class="icon-ok"></i> Submit Lesson!
</button>
  </div>

<% end %>

upload-lesson/app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

upload-lesson/app/views/lessons/index.html.erb
<h1>Listing All Lessons</h1>

<div class="row">
<div class="span8">

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Title</th>
    <th>Goal</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.title %></td>
    <td><%= lesson.goal %></td>
   <% t = Course.find(lesson.course_id)%>
     <td> <%= link_to t.name, course_path(t) %></td>
    <td><%= link_to 'Show', lesson %></td>
    <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
    <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
</div>
</div>

upload-lesson/app/views/lessons/new.html.erb
 <div class="hero-unit">
<h1>Create a New Lesson!</h1>
<br>

<%= render 'form' %>
</div>
<%= link_to 'Back', lessons_path %>

upload-lesson/app/views/lessons/show.html.erb
<div class="row">

  <div class="span4">
   
   <p id="notice"><%= notice %></p>
   <p>    <% t = Course.find(@lesson.course_id) %>
    <h2><%= t.name %></h2>


   </p>
   <p>
   <b>Lesson Title:</b>
   <%= @lesson.title %>
   </p>

   <b>Goal:</b>
   <%= @lesson.goal %>
   </p>
    
    </div>

  <div class="span4">
  <% if @lesson.assets.any? %>
   <center><h3>Attachments</h3></center>
   
  <% else %>
   <center><i>No attachments exist for this lesson.</i></center>
  <% end %>

   <table class="table table-striped table-bordered table-condensed">

   <% for asset in @lesson.assets %>
    <tr>
    <td><%= asset.attachment_file_name %></td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
    <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    </table>
  <% if @lesson.assets.any? %>
    <%= link_to "Download All", :controller => "lessons", :action => "download", :file_name => "#{@lesson.id}" %>
   <% end %>
   </div>
  </div>


<div>
<h3>
<%= link_to "+Add Attachment!", :controller => "assets", :action => "new", :lesson_id => @lesson %>
</h3>

<%= link_to 'Edit Lesson', edit_lesson_path(@lesson) %> |
<%= link_to "Back to Course", course_path(@lesson.course_id) %>
  <% if @lesson.assets.any? %>
<% @lesson.bundle %>
 <% end %>

</div>