upload-lesson/config/routes.rb
UploadLesson::Application.routes.draw do
  resources :assets
  resources :lessons
  resources :courses, :has_many => :comments
  
  root :to => "home#index"
  match "home" => "home#index"
  match "download" => "lessons#download"
  match "downloadcourse" => "courses#downloadcourse"

end

upload-lesson/app/models/asset.rb
#This class was made so that a Lesson can have multiple attachments
#Essentially, each Asset is really just an attachment
class Asset < ActiveRecord::Base
  attr_accessible :lesson_id, :attachment

#allows us to use :lesson_id in the :url
Paperclip.interpolates :lesson_id do |attachment, style|
    attachment.instance.lesson_id
    end

  has_attached_file :attachment,
 :url => "/attachments/:lesson_id/:basename.:extension",
 :path => ":rails_root/public/attachments/lessons/:lesson_id/:basename.:extension", :dependent => :destroy
 
#an asset should not exist without an attachment
 validates_attachment_presence :attachment

end

upload-lesson/app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @asset = Asset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.json
  def new
  @asset = Lesson.find(params[:lesson_id]).assets.build 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to lesson_path(@asset.lesson_id), notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.json
  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to lesson_path(@asset.lesson_id) }
      format.json { head :no_content }
    end
  end
end

upload-lesson/app/helpers/assets_helper.rb
module AssetsHelper
end

upload-lesson/app/views/assets/_form.html.erb
<%= form_for(@asset, :remote => true) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= f.hidden_field :lesson_id %>
  </div>
  <div class="field">
   
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
   <button type="submit" class="btn btn-primary">
  <i class="icon-ok"></i> Attach File!
</button>
  </div>


<% end %>

upload-lesson/app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to "Back", lesson_path(@asset.lesson_id) %>

upload-lesson/app/views/assets/index.html.erb
<h1>Listing Attachments</h1>

   <table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>From Lesson</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td><%= asset.lesson_id %></td>
    <td><%= asset.attachment_file_name %></td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
    <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asset', new_asset_path %>

upload-lesson/app/views/assets/new.html.erb
<h1>Add Attachment</h1>

<%= render 'form' %>

<%= link_to "Back", lesson_path(@asset.lesson_id) %>

upload-lesson/app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <% t = Lesson.find(@asset.lesson_id) %>
  <% c = Course.find(t.course_id) %>
  <b>Course:</b>
  <%= c.name %> <br>
  <b>Lesson:</b>
  <%= t.title %>
</p>

<p>
  <b>FileName:</b>
  <%= @asset.attachment_file_name %>
</p>




<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to "Back", lesson_path(@asset.lesson_id) %>