upload-lesson/config/routes.rb
UploadLesson::Application.routes.draw do
  resources :assets
  resources :lessons
  resources :courses, :has_many => :comments
  
  root :to => "home#index"
  match "home" => "home#index"
  match "download" => "lessons#download"
  match "downloadcourse" => "courses#downloadcourse"

end

upload-lesson/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    #2.times {@course.lessons.build}
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    #2.times {@course.lessons.build}
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    @course_id = params[:id]
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])

#destroy lessons belonging to course
    @course.lessons.each {
      |lesson|
        lesson.assets.destroy
        FileUtils.rm_rf "#{Rails.root}/public/attachments/lessons/#{lesson.id}" #destroy folder belonging to that lesson
        lesson.destroy
    }

    FileUtils.remove_file "#{Rails.root}/public/attachments/courses/#{@course.name}.zip" #remove the courses Zipfile
    @course.destroy #destroy course object
     
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
  def downloadcourse
   t = Course.find(params[:theid])
   send_file "#{Rails.root}/public/attachments/courses/#{t.name}.zip", :type=>"application/zip" 
  end

end

upload-lesson/app/helpers/courses_helper.rb
module CoursesHelper
end

upload-lesson/app/views/courses/_form.html.erb
<%= form_for(@course, :html => { :multipart => true}) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Name.." %>
      Name of Course
  </div>
  <div class="field">
    <%= f.text_field :subject, :placeholder => "Subject.." %> 
     Subject of Course
  </div>
  <div class="field">

    <%= f.text_field :description, :placeholder => "Description.." %> 
     Course Description
  </div>

  <div class="actions">
<button type="submit" class="btn btn-primary">
  <i class="icon-ok"></i> Submit Course!
</button>
  </div>
<% end %>

upload-lesson/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

upload-lesson/app/views/courses/index.html.erb
<h2><center>Listing Of All Courses!</center></h2>


<div class="row">
<div class="span11">
<center>
<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th><center>Name</center></th>
    <th><center>Subject</center></th>
    <th><center>Description</center></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td width = 120><center><%= course.name %></center></td>
    <td width = 150><center><%= course.subject %></center></td>
    <td width = 150><center><%= course.description %></center></td>

    <td width = 40><center><%= link_to 'Show', course %></center></td>
    <td width = 40><center><%= link_to 'Edit', edit_course_path(course) %></center></td>
    <td width = 40><center><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
  </tr>
<% end %>
</table>

</center>
<br />
</div>
</div>
<center><%= button_to('+Create A New Course', new_course_path, :method => :get, :class => 'btn btn-primary')  %></center>

upload-lesson/app/views/courses/new.html.erb
 <div class="hero-unit">
<h1>Create a New Course!</h1>
<br>
<p><i>Please fill out the appropriate fields in order to create your course.</i></p>


      <!-- Main hero unit for a primary marketing message or call to action -->
     
<%= render 'form' %>
</div>


<%= button_to('Back', courses_path) %>

upload-lesson/app/views/courses/show.html.erb
 <div class="row">

  <div class="span4">
    <p id="notice"><%= notice %></p>
      
    <p>
      
      <h2><%= @course.name %></h2>
       <% if @course.lessons.any? %>

   <% end %>
   </p>

    <p>
      <b>Subject:</b>
      <%= @course.subject %>
   </p>

    <p>
      <b>Description:</b>
      <%= @course.description %>
   </p>

<h3><%= link_to "+Create New Lesson!", :controller => "lessons", :action => "new", :course_id => @course %></h3>
  <br>



<%= link_to 'Edit Course', edit_course_path(@course) %> |
<%= link_to 'Back to Courses', courses_path %>
  </div>

  <div class="span4">
  <% if @course.lessons.any? %>
   <h2><center>Lessons<center></h2>
     <table class="table table-striped table-bordered table-condensed">



<% @course.lessons.each do |lesson| %> 

    <tr><td><%= link_to lesson.title, lesson_path(lesson) %> /
    <%= lesson.goal %></td></tr>
     <td><%= link_to 'View', lesson %> |
     <%= link_to 'Remove', lesson, :confirm => 'Are you sure>', :method => :delete %></td>
     </tr>
    <% end %>
 
</table>
     <% else %>
     <center><i>No lessons exist for this course</i></center>
     <% end %>
<% if @course.lessons.any? %>
  <%= link_to "Download Course", :controller => "courses", :action => "downloadcourse", :theid => "#{@course.id}" %>
<% end %>
</div>

</div>

<% button_to("+New Lesson!", :controller => "lessons", :action => "new", :course_id => @course, :method => :post, :class => 'btn btn-primary')  %>

<% @course.bundle %>